// <auto-generated />
namespace ResumeBuilder_1291763.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MKDO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MKDO));
        
        string IMigrationMetadata.Id
        {
            get { return "202601170400284_MKDO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
